### ISSUE TITLE
File Type Detection

### ISSUE THREAD

**Issue by philsinatra** [philsinatra/HTML-Nest-Comments#1]
Detect the file type of the executing file and verify it should be using HTML comments. If not - do not execute the comment commands and possible display feedback. 

Intended supported file types:
- .html
- .php

**Comment by evanre** [comment]
@philsinatra Hi, I have a problem with your plugin. After installing it i got only one type of commenting in all files: `html`, `php`, `js`, `css`, `scss` etc. When I press `ctrl-shift-/` i got `<!--...-->`. And it looks like this:

```
<!--.block {
    display: block;
}-->
```

```
$("#nav-ham").click(function(event) {
        <!--event.preventDefault();
        mainNav.open;-->
    });
```

Help me please to define yur pluggin only for `html`/`php` files. Thanks for help.

**Comment by philsinatra** [comment]
The plugin is specifically design for HTML style nested comments only. You should be using the built in commenting function for .css and .js files, which can handle nesting comments without an issue.
