### ISSUE TITLE
Plan for vscode?

### ISSUE THREAD

**Issue by usernamehw** [philsinatra/HTML-Nest-Comments#5]
Hi, I was wondering if you want to write the same extension for [visual studio code editor](https://github.com/Microsoft/vscode), if not, I'd like to do it (using the same syntax):

`<!--`|`<!~~`|
--- | --- |
`-->` | `~~>` |

BTW, I think your description for sublime text package is broken (https://packagecontrol.io/packages/HTML%20Nest%20Comments) - the `What Happens` part.

**Comment by philsinatra** [comment]
I actually am planning to build the extension for VSCode, just haven't gotten to it yet.

The description in Sublime's Package Control page has never rendered properly. It's actually rendering as a comment which is why it's not showing up. Probably a quick encoding fix, I'll take a look.

**Comment by philsinatra** [comment]
https://marketplace.visualstudio.com/items?itemName=philsinatra.html-nested-comments
